### ISSUE TITLE
Can ble-host be used to implement a Windows L2CAP client?

### ISSUE THREAD

**Issue by SamKacer** [Emill/node-ble-host#2]
Hello,

this library seems very interesting. It is particularly very promising as it seems to provide functionality for L2CAP, which other node.js libraries don't seem to.

I think in the readme this is probably already answered, but wanted to ask to make sure. Would this lib only work for programming BLE clients running on Linux or could it possibly work on Windows as well.

My particular usecase is I need to be able to create an L2CAP client to read a stream of data from a BLE device. preferably if the client could run on Windows. It does not need to host BLE, just consume it as a client.

Info on this greatly appreciated!

**Comment by Emill** [comment]
The library itself is independent of platform. You will however need a library/driver that can communicate with a Bluetooth controller. In the readme I currently only have instructions how that can be done in Linux.

For Windows I guess you could use https://github.com/abandonware/node-bluetooth-hci-socket#windows, but I haven't tried that. The idea is to bypass Windows's own Bluetooth stack (which doesn't support L2CAP CoC as far as I know) and talk directly to the controller over USB.

**Comment by SamKacer** [comment]
@Emill  thanks for the info. quite disapointing windows does not support this at the moment.
