### ISSUE TITLE
minor: typo in AdvertisingDataBuilder example

### ISSUE THREAD

**Issue by MikiNacucchi** [Emill/node-ble-host#9]
I was running this example and there seems to be a typo in the module name
https://github.com/Emill/node-ble-host/blob/master/docs/api/advertising-data-builder.md

`const NodeBleHost = require('node-ble-host');`

Should be
`const NodeBleHost = require('ble-host');`

**Comment by MikiNacucchi** [comment]
Same thing in "Att errors" example https://github.com/Emill/node-ble-host/blob/master/docs/api/att-errors.md

The other examples seems fine.

**Comment by Emill** [comment]
Thanks for the report. Will fix.
